/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Konfigurasi.koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kholid
 */
public class g_RiwayatPesanan extends c_Menu {
    private DefaultTableModel DftTblModel_riwayat;
    private String SQL;

    /**
     * Creates new form h_KonfirmasiPesanan
     */
    public g_RiwayatPesanan() {
        initComponents();
        this.TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGKonfirmasiPesanan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        t_riwayat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BGKonfirmasiPesanan.setBackground(new java.awt.Color(1, 22, 39));
        BGKonfirmasiPesanan.setPreferredSize(new java.awt.Dimension(650, 500));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 255, 252));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RIWAYAT PESANAN");

        t_riwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pesanan", "Nama", "No. Hp", "Alamat", "Kostum", "Merk", "Tanggal", "Harga"
            }
        ));
        jScrollPane2.setViewportView(t_riwayat);

        javax.swing.GroupLayout BGKonfirmasiPesananLayout = new javax.swing.GroupLayout(BGKonfirmasiPesanan);
        BGKonfirmasiPesanan.setLayout(BGKonfirmasiPesananLayout);
        BGKonfirmasiPesananLayout.setHorizontalGroup(
            BGKonfirmasiPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGKonfirmasiPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BGKonfirmasiPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        BGKonfirmasiPesananLayout.setVerticalGroup(
            BGKonfirmasiPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BGKonfirmasiPesananLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BGKonfirmasiPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BGKonfirmasiPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TampilData(){
        DftTblModel_riwayat = new DefaultTableModel ();
        DftTblModel_riwayat.addColumn("ID PESANAN");
        DftTblModel_riwayat.addColumn("NAMA");
        DftTblModel_riwayat.addColumn("NO. HP");
        DftTblModel_riwayat.addColumn("ALAMAT");
        DftTblModel_riwayat.addColumn("KOSTUM");
        DftTblModel_riwayat.addColumn("MERK");
        DftTblModel_riwayat.addColumn("TANGGAL");
        DftTblModel_riwayat.addColumn("HARGA");
        t_riwayat.setModel(DftTblModel_riwayat);
        Connection conn = koneksi.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from riwayatpesanan";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()){
                DftTblModel_riwayat.addRow(new Object[]{
                    res.getString("id_pesanan"),
                    res.getString("nama_pelanggan"),
                    res.getString("nohp_pelanggan"),
                    res.getString("alamat_pelanggan"),
                    res.getString("kostum_pesanan"),
                    res.getString("merk_kostum_pesanan"),
                    res.getString("tanggal_pesanan"),
                    res.getString("harga_total_pesanan"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
    }}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(g_RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(g_RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(g_RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(g_RiwayatPesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new g_RiwayatPesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BGKonfirmasiPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable t_riwayat;
    // End of variables declaration//GEN-END:variables
}
