/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.pertemuan4;

/**
 *
 * @author D-17
 */
public class P4 extends javax.swing.JFrame {
    String nama, nim, jk, umur, hobi, alamat;

    /**
     * Creates new form P4
     */
    public P4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dNama = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dJK = new javax.swing.JComboBox<>();
        Hapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        dHasil = new javax.swing.JTextArea();
        dAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dUmur = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dNim = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dHobi = new javax.swing.JTextField();

        jToggleButton1.setText("jToggleButton1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama:");

        jLabel2.setText("Jenis Kelamin (L/P):");

        jLabel3.setText("Alamat:");

        dNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNamaActionPerformed(evt);
            }
        });

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        jLabel4.setText("BIODATA");

        dJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L", "P" }));
        dJK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dJKActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        dHasil.setColumns(20);
        dHasil.setRows(5);
        jScrollPane2.setViewportView(dHasil);

        dAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dAlamatActionPerformed(evt);
            }
        });

        jLabel5.setText("Umur:");

        dUmur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Tahun", "2 Tahun", "3 Tahun", "4 Tahun", "5 Tahun", "6 Tahun", "7 Tahun", "8 Tahun", "9 Tahun", "10 Tahun", "11 Tahun", "12 Tahun", "13 Tahun", "14 Tahun", "15 Tahun", "16 Tahun", "17 Tahun", "18 Tahun", "19 Tahun", "20 Tahun", "21 Tahun", "22 Tahun", "23 Tahun", "24 Tahun", "25 Tahun", "26 Tahun", "27 Tahun", "28 Tahun", "29 Tahun", "30 Tahun", "31 Tahun", "32 Tahun", "33 Tahun", "34 Tahun", "35 Tahun", "36 Tahun", "37 Tahun", "38 Tahun", "39 Tahun", "40 Tahun", "41 Tahun", "42 Tahun", "43 Tahun", "44 Tahun", "45 Tahun", "46 Tahun", "47 Tahun", "48 Tahun", "49 Tahun", "50 Tahun", "51 Tahun", "52 Tahun", "53 Tahun", "54 Tahun", "55 Tahun", "56 Tahun", "57 Tahun", "58 Tahun", "59 Tahun", "60 Tahun", "61 Tahun", "62 Tahun", "63 Tahun", "64 Tahun", "65 Tahun", "66 Tahun", "67 Tahun", "68 Tahun", "69 Tahun", "70 Tahun", "71 Tahun", "72 Tahun", "73 Tahun", "74 Tahun", "75 Tahun", "76 Tahun", "77 Tahun", "78 Tahun", "79 Tahun", "80 Tahun", "81 Tahun", "82 Tahun", "83 Tahun", "84 Tahun", "85 Tahun", "86 Tahun", "87 Tahun", "88 Tahun", "89 Tahun", "90 Tahun", "91 Tahun", "92 Tahun", "93 Tahun", "94 Tahun", "95 Tahun", "96 Tahun", "97 Tahun", "98 Tahun", "99 Tahun", "100 Tahun", "101 Tahun", "102 Tahun", "103 Tahun", "104 Tahun", "105 Tahun", "106 Tahun", "107 Tahun", "108 Tahun", "109 Tahun", "110 Tahun", "111 Tahun", "112 Tahun", "113 Tahun", "114 Tahun", "115 Tahun", "116 Tahun", "Lebih dari 116 Tahun" }));
        dUmur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dUmurActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\D\\Downloads\\channels4_profile.jpg")); // NOI18N

        jLabel7.setText("Nim:");

        dNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dNimActionPerformed(evt);
            }
        });

        jLabel8.setText("Hobi:");

        dHobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dHobiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(230, 230, 230))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dAlamat)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dNama, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Proses)
                                                .addGap(18, 18, 18)
                                                .addComponent(Hapus)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dNim, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dJK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dUmur, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(dHobi, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(299, 299, 299)))))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dNama))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dNim))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dUmur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(dHobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proses)
                    .addComponent(Hapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        nama = dNama.getText();
        nim = dNim.getText();
        jk = dJK.getSelectedItem().toString();
        umur = dUmur.getSelectedItem().toString();
        hobi = dHobi.getText();
        alamat = dAlamat.getText();
        dHasil.setText("Nama \t\t = " + nama
                +"\nNim \t\t = " + nim
                +"\nJenis Kelamin \t\t = " + jk 
                +"\nUmur \t\t = " + umur 
                +"\nHobi \t\t = " + hobi
                +"\nAlamat \t\t = " + alamat);
    }//GEN-LAST:event_ProsesActionPerformed

    private void dNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNamaActionPerformed

    private void dJKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dJKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dJKActionPerformed

    private void dAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dAlamatActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        dNama.setText("");
        dNim.setText("");
        dJK.setSelectedItem("");
        dUmur.setSelectedItem("");
        dHobi.setText("");
        dAlamat.setText("");
        dHasil.setText("");
    }//GEN-LAST:event_HapusActionPerformed

    private void dUmurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dUmurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dUmurActionPerformed

    private void dNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dNimActionPerformed

    private void dHobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dHobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dHobiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Proses;
    private javax.swing.JTextField dAlamat;
    private javax.swing.JTextArea dHasil;
    private javax.swing.JTextField dHobi;
    private javax.swing.JComboBox<String> dJK;
    private javax.swing.JTextField dNama;
    private javax.swing.JTextField dNim;
    private javax.swing.JComboBox<String> dUmur;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
